FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
    ncbi-blast+ \
    bedtools \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN useradd -m periodUser \
    && chown -R periodUser /app \
    && chmod +x /app/reindex_vcf.sh

USER periodUser

CMD ["bash"]