FROM rocker/tidyverse:4.4.2

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev \
    libssl-dev \
    libfontconfig1-dev \
    libxml2-dev \
    libharfbuzz-dev \
    libfreetype-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    procps \
    && rm -rf /var/lib/apt/lists/*

COPY ./*.R /

RUN chmod +x /lollipop_graph.R

RUN Rscript packages.R

CMD ["bash"]
